name: start_image_picker
description: A better Flutter plugin for selecting images from the Android and iOS image
  library, and taking new pictures with the camera.
author: Nan Yang <qazyn951230@gmail.com>
homepage: https://github.com/qazyn951230/start_point_flutter/tree/master/packages/start_image_picker

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.undev.start_image_picker
    pluginClass: StartImagePickerPlugin
